theme: jekyll-theme-cayman
title: Jonathan Li's homepage
description: Know what you know, know what you do not know. That is true knowledge
# Premature optimization is the root of all evil #Bookmark this to keep an eye on recent developments!

